version: '3.8'

services:
  postgres:
    image: postgres
    container_name: mamba_db
    environment:
      NODE_ENV: development
      POSTGRES_DB: mamba-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mamba-db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: 
      context: ./api
      target: development
    container_name: mamba_api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: development
      DATABASE_URL: "postgresql://user:password@postgres:5432/mamba-db?schema=public"
      PORT: 3001
    ports:
      - "3001:3001"
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npx prisma migrate deploy && npx prisma generate && yarn && yarn start:dev"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/v1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: mamba_client
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "5174:5174"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://api:3001/api/v1

volumes:
  postgres-data: 